<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="preferences"
    nsURI="http://www.eclipse.org/dltk/tcl/activestatedebugger.ecore" nsPrefix="org.eclipse.dltk.tcl.activestatedebugger">
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementPattern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="handleIdentifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="include" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstrumentationConfig">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElements" upperBound="-1"
        eType="#//ModelElementPattern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//InstrumentationMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InstrumentationMode">
    <eLiterals name="DEFAULT"/>
    <eLiterals name="SOURCES" value="1"/>
    <eLiterals name="SELECTION" value="2"/>
  </eClassifiers>
</ecore:EPackage>
